project: 
  type: website
  output-dir: docs

website:
  title: "Edward(Eddie) Cruz,Jr.  Data Analysis Portfolio"
  navbar:
    left:
      - text: "About Me"
        file: aboutme.qmd
      - text: "Projects"
        menu:
          - text: "Group10 Analysis Exercise"
            file: starter-analysis-exercise/products/report/manuscript_final-2.qmd
          - text: "R Coding Exercise"
            file: coding-exercise/coding-exercise.qmd
          - text: "CDC Data Exercise"
            file: cdcdata-exercise/cdcdata-exercise.qmd
          - text: "Eddies Data Exercise"
            file: data-exercise/data-exercise.qmd
          - text: "Presentation Exercise"
            file: presentation-exercise/presentation-exercise.qmd
          - text: "Tidy Tuesday Exercise"
            file: tidytuesday-exercise/tidytuesday-exercise.qmd
          
    right:
      - icon: github 
        href: https://github.com/ecruz0369/ecruz0369-P2-Practicum-II-Portfolio-EdwardCruz       

format:
  html:
    theme: Zephyr
    highlight: zenburn
    css: styles.css
    toc: FALSE


